<a href="https://colab.research.google.com/github/Marshud/ml-classes-01/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

data = [[1,2,3], [4,5,6]]
my_tensor = torch.tensor(data)

print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
shape = (2, 3)

ones = torch.ones(shape)
zeros = torch.zeros(shape)
random = torch.randn(shape)

print(f"Random Tensor: \n {random}")

Random Tensor: 
 tensor([[ 0.3345,  1.2444, -0.3081],
        [ 0.5798,  0.2419,  0.4379]])


In [ ]:
template = torch.tensor([[1,2], [3,4]])

rand_like = torch.randn_like(template, dtype=torch.float)

print(f"Template Tensor: \n {template} \n")
print(f"Randn_like tensor: \n {rand_like}")

Template Tensor: 
 tensor([[1, 2],
        [3, 4]]) 

Randn_like tensor: 
 tensor([[-0.0816, -0.1935],
        [-0.4657,  0.3068]])


In [ ]:
tensor = torch.randn(2, 3)

print(f"Shape: {tensor.shape}")
print(f"Datatype: {tensor.dtype}")
print(f"Device: {tensor.device}")

Shape: torch.Size([2, 3])
Datatype: torch.float32
Device: cpu


In [ ]:
x_data = torch.tensor([[1., 2.], [3., 4.]]) # Data tensor

w = torch.tensor([[1.0], [2.0]], requires_grad=True) # Parameter tensor

print(f"Data tenspr requires_grad: {x_data.requires_grad}")
print(f"Parameter tensor requires_grad: {w.requires_grad}")

Data tenspr requires_grad: False
Parameter tensor requires_grad: True


In [ ]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)

y = a + b

z = x * y

print(f"Result Z: {z}")

Result Z: 20.0


In [ ]:
print(f"grad_fn for z: {z.grad_fn}")
print(f"grad_fn for y: {y.grad_fn}")
print(f"grad_fn for a: {a.grad_fn}")

grad_fn for z: <MulBackward0 object at 0x7cc2f5879cf0>
grad_fn for y: <AddBackward0 object at 0x7cc2f5879cf0>
grad_fn for a: None


In [ ]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[10, 20], [30, 40]])

element_wise_product = a * b # Matrices must match(1*10, 2*20, 3*30, 4*40)
print(element_wise_product)


tensor([[ 10,  40],
        [ 90, 160]])


In [ ]:
# Using the @ in multiplicaltion requires m1 rows = m2 columns
m1 = torch.tensor([[1, 2, 3], [4, 5, 6]]) # Shape (2,3)
m2 = torch.tensor([[7, 8], [9, 10], [11, 12]]) # Shape (3,2)

matrix_product = m1 @ m2

print(matrix_product)

tensor([[ 58,  64],
        [139, 154]])


In [ ]:
scores = torch.tensor([[10., 20., 30.], [5., 10., 15.]])
# To get the scores for each assignment, we collapse the student dimension (dim=0)
avg_per_assignment = scores.mean(dim=0)
print(f"Average per assignment (dim=0): {avg_per_assignment}")

#To get average for each student, we collapse the assignment dimension (dim=1)
avg_per_student = scores.mean(dim=1)
print(f"Average per student (dim=1): {avg_per_student}")



Average per assignment (dim=0): tensor([ 7.5000, 15.0000, 22.5000])
Average per student (dim=1): tensor([20., 10.])


In [ ]:
x = torch.arange(12).reshape(3,4)
col_2 = x[:, 2]
col_2

tensor([ 2,  6, 10])

In [ ]:
scores = torch.tensor([
    [10,0, 5, 20, 1],
    [1, 30, 2, 5, 0]
])

best_indices = torch.argmax(scores, dim=1)
best_indices

tensor([3, 1])

In [ ]:
# Gathering elements from different positions within a tensor
data = torch.tensor([
    [10, 11, 12, 13],
    [20, 21, 22, 23],
    [30, 31, 32, 33]
])

indicies_to_select = torch.tensor([[2], [0], [3]])

selected_values = torch.gather(data, dim=1, index=indicies_to_select)
selected_values

tensor([[12],
        [20],
        [33]])

In [ ]:
N=10 # Batch of data will have 10 data points

# Each data point has 1 input feature and 1 output value
D_in = 1
D_out = 1

#Create our input data X
X = torch.randn(N, D_in)

#Create our true target lables y by using the "true" W and b
# The "true" W is 2.0. the "true" b is 1.0
true_W = torch.tensor([[2.0]])
true_b = torch.tensor(1.0)
y_true = X @ true_W + true_b + torch.randn(N, D_out) * 0.1 # Add a little noise

# Initailize our parameters with random values.
# Shapes must be corret for matrix multiplication!
W = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(f"Inital Weight W: \n {W} \n")
print(f"Initial Bias b: \n {b}")

Inital Weight W: 
 tensor([[-0.3060]], requires_grad=True) 

Initial Bias b: 
 tensor([-0.2618], requires_grad=True)


In [ ]:
y_hat = X @ W + b # From the linear regression formula

# Forward pass through our model
y_hat = model(X_train)

In [ ]:
# Mean Squared Errror
error = y_hat - y_true
squared_error = error ** 2
loss = squared_error.mean()

# Compute gradients
loss.backward()
'''
The results of this operation is the .grad attribute on both the W and the b
'''




In [ ]:
# Learning Process in Pytorch in raw form
#Hyperparameters
learning_rate, epochs = 0.01, 100

# Re-initialize parameters
W, b = torch.randn(1, 1, requires_grad=True), torch.randn(1, requires_grad=True)

# Training Loop
for epoch in range(epochs):
  # Forward pass and loss
  y_hat = X @ W + b
  loss = torch.mean((y_hat - y_true)**2)

  # Backward pass
  loss.backward()

  # Update parameters (gradient discent)
  with torch.no_grad():
    W -= learning_rate * W.grad; b -= learning_rate * b.grad

  # Zero gradients
  W.grad.zero_(); b.grad.zero_()

In [ ]:
import torch
# Learning Process Refined
D_in = 1
D_out = 1
X = torch.randn(10,1)
#Create a linear layer
linear_layer = torch.nn.Linear(in_features=D_in, out_features=D_out)

# Look inside
print(f"Layer's Weight (W): {linear_layer}\n")
print(f"Laye's Bias (b): {linear_layer.bias} \n")

# You use it like a function. This is the forward pass.
#Assume X is a tensor of shape [10, 1]
y_hat_nn = linear_layer(X)

print(f"Out of nn.Linear (first 3 rows): \n {y_hat_nn[:3]}")

Layer's Weight (W): Linear(in_features=1, out_features=1, bias=True)

Laye's Bias (b): Parameter containing:
tensor([-0.2969], requires_grad=True) 

Out of nn.Linear (first 3 rows): 
 tensor([[-0.2873],
        [-0.5112],
        [-0.3373]], grad_fn=<SliceBackward0>)


In [ ]:
# ReLU - Rectified Linear Unit (Introduced to make Linear models more flexible)
relu = torch.nn.ReLU()
sample_data = torch.tensor([-2.0, -0.5, 0.0, 0.5, 2.0])
activated_data = relu(sample_data)

print(f"Original Data: {sample_data}")
print(f"Data after ReLU: {activated_data}")

Original Data: tensor([-2.0000, -0.5000,  0.0000,  0.5000,  2.0000])
Data after ReLU: tensor([0.0000, 0.0000, 0.0000, 0.5000, 2.0000])


In [ ]:
# GELU - Gausisian Error Linear Unit - mainly used for Modern Transformers and a smooother version of ReLU
gelu = torch.nn.GELU()
sample_data = torch.tensor([-2.0, -0.5, 0.0, 0.5, 2.0])
activated_data = gelu(sample_data)

print(f"Original Data: {sample_data}")
print(f"Data after ReLU: {activated_data}")

Original Data: tensor([-2.0000, -0.5000,  0.0000,  0.5000,  2.0000])
Data after ReLU: tensor([-0.0455, -0.1543,  0.0000,  0.3457,  1.9545])


In [ ]:
# nn.Softmax
softmax = torch.nn.Softmax(dim=-1)

# Raw model scores for 2 items, accross 4 possible classes
logits = torch.tensor([[1.0, 3.0, 0.5, 1.5], [-1.0, 2.0, 1.0, 0.0]])
probabilities = softmax(logits)

print(f"Output Probabilities: \n {probabilities} \n")
print(f"Sum of probabilities for item 1: {probabilities[0].sum()}")

Output Probabilities: 
 tensor([[0.0939, 0.6942, 0.0570, 0.1549],
        [0.0321, 0.6439, 0.2369, 0.0871]]) 

Sum of probabilities for item 1: 1.0


In [ ]:
# nn.Embedding
vocab_size = 10 # Our language has 10 unique words
embedding_dim = 3 #We'll represent each word with a 3D vector

embedding_layer = torch.nn.Embedding(vocab_size, embedding_dim)

input_ids = torch.tensor([[1, 5, 0, 8]])
word_vectors = embedding_layer(input_ids)




In [ ]:
# NN.LayerNorm
norm_layer = torch.nn.LayerNorm(normalized_shape=3)
input_features = torch.tensor([[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]])
normalized_features = norm_layer(input_features)

print(f"Normalized Features: {normalized_features}\n")
print(f"Mean (should be ~0): {normalized_features.mean(dim=-1)}")
print(f"Std Dev (should be ~1): {normalized_features.std(dim=-1)}")

Normalized Features: tensor([[[-1.2247,  0.0000,  1.2247],
         [-1.2247,  0.0000,  1.2247]]], grad_fn=<NativeLayerNormBackward0>)

Mean (should be ~0): tensor([[0., 0.]], grad_fn=<MeanBackward1>)
Std Dev (should be ~1): tensor([[1.2247, 1.2247]], grad_fn=<StdBackward0>)


In [ ]:
# Linear Regression Module
import torch.nn as nn

#Inherit from nn.Module
class LinearRegressionModel(nn.Module):
  def __init__(self, in_features, out_features):
    super().__init__()
    # In the constructor, we DEFINE the layers we'll use.
    self.linear_layer = nn.Linear(in_features, out_features)

  def forward(self, x):
    # In the forward pass we connect the layers
    return self.linear_layer(x)

# Instantiate the model
model = LinearRegressionModel(in_features=1, out_features=1)
print("Model Architecture".center(30, "="))
print(model)

======Model Architecture======
LinearRegressionModel(
  (linear_layer): Linear(in_features=1, out_features=1, bias=True)
)


In [ ]:
# Optimizers
import torch.optim as optim

#Hyperparameters
learning_rate = 0.01

# Create an Adam optimizer.
# We pass model.paramters() to tell it which tensors to manage
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

#We'll also grab a pre-built loss function from torch.nn
loss_fn = nn.MSELoss() # Mean Squared Error Loss


In [ ]:
epochs = 100

for epoch in range(epochs):
  #Forward Pass
  y_hat = model(X)

  #Calculate the Loss
  loss = loss_fn(y_hat, y_true)

  # 3 LINE COMBO
  #1. Zero the gradients
  optimizer.zero_grad()
  #2. Compute gradients
  loss.backward()
  #3. Update the parameters
  optimizer.step()

  #Optional: print progress
  if epoch % 10 == 0:
    print(f"Epoch {epoch:02d}: Loss={loss.item():.4f}")

NameError: name 'y_true' is not defined

In [ ]:
# The Feed-Forward Network(FFN)
import torch.nn as nn

class FeedForwardNetwork(nn.Module):
  def __init__(self, embedding_dim, ffn_dim):
    super().__init__()
    # In an LLM, embedding_dim might be 4096, ffn_dim might be 14336

    #We use what we know
    self.layer1 = nn.Linear(embedding_dim, ffn_dim)
    self.activation = nn.GELU()
    self.layer2 = nn.Linear(ffn_dim, embedding_dim)

  def forward(self, x):
    # The data flow as expected
    x = self.layer1(x)
    x = self.activation(x)
    x = self.layer2(x)
    return x